### PR TITLE
Remove deprecations from SpringBoot 1.4

### PR DESCRIPTION
**Pull request by busches**
Remove deprecated @SpringApplicationConfiguration in favor of using @SpringBootTest added in SpringBoot 1.4. Upon switching to SpringBoot 1.4 there were other deprecations that I've also removed, additionally tests were failing before I started.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@busches Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-bookmarks&pullRequestId=25)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-bookmarks&pullRequestId=25) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@busches Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-bookmarks&pullRequestId=25)!

**Comment by gregturn** [comment]
Resolves via https://github.com/spring-guides/tut-bookmarks/commit/fbb3cc6592944a4f1ff68685fe9f2676ce29c604

**Comment by busches** [comment]
Any feedback on why you duplicated my effort instead of merging the PR? I'd love to not waste either of our time in the future.

**Comment by gregturn** [comment]
Sorry. I ran a script that hits all guides at once. In fixing five other guides I hit this as well. Also made some other tweaks coordinating with the Boot team. That was before I spotted your PR. Seemed easier to push on through instead of picking apart the diffs.

**Pull request closed without merging**
