### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by roryp**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@roryp Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-bookmarks&pullRequestId=45)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-bookmarks&pullRequestId=45) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by dsyer** [comment]
What made you think it would be an MIT license? All the Getting Started guides have this at the bottom:

> All guides are released with an ASLv2 license for the code, and an Attribution, NoDerivatives creative commons license for the writing.

I would assume it is the same (but the link is missing from this guide).

**Comment by roryp** [comment]
thanks. i didnt see the ASLv2 license details.

**Comment by gregturn** [comment]
Additionally there are existing license files for both the code and the copy.

**Pull request closed without merging**
